---
- hosts: pods
  become: true
  gather_facts: no
  tasks:
  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

  - name: Add Docker GPG apt Key
    shell: 'curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg'

  - name: Add Docker Repository
    shell: 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian buster stable" | tee /etc/apt/sources.list.d/docker.list'

  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest

  - name: Install Docker apt package
    apt:
      pkg: docker-ce
      state: latest
      update_cache: yes
    become: true

  - name: Ensure Docker service is installed and restarted
    service:
      name: docker
      state: restarted
      enabled: yes

  - name: Install pip
    apt:
      name: python3-pip
      state: latest

  - name: Install pip packages
    pip: name={{ item }}
    loop:  ['setuptools==58.0.1', 'wheel', 'pycparser']

  - name: Install Docker Compose
    shell: 'pip3 install docker-compose'

  - name: Install Docker Module for Python
    pip:
      name: docker

 